Putting unfiltered tests in foreground.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -474,27 +474,27 @@ jobs:
           dotnet test --filter Category=MemoryLifeCycle --blame-hang-timeout 5m MonoGame.Tests.dll > dx12_memory_lifecycle_test_result.log 2>&1 &
           PID3=$!
           
-          dotnet test --filter "Category!=Audio&Category!=GraphicsDevice&Category!=MemoryLifeCycle" --blame-hang-timeout 5m MonoGame.Tests.dll > dx12_remaining_test_result.log 2>&1 &
-          PID4=$!
+          # 2. Run the last test suite in foreground
+          echo "======== Running all tests except Audio, GraphicsDevice, MemoryLifeCycle ========"
+          dotnet test --filter "Category!=Audio&Category!=GraphicsDevice&Category!=MemoryLifeCycle" --blame-hang-timeout 5m MonoGame.Tests.dll
+          STATUS4=$?
+
+          # 3. Wait for ech background processes to finish and print results
+          STATUS1=0; STATUS2=0; STATUS3=0
           
-          # 2. Wait for ech background processes to finish and print results
-          wait $PID1; STATUS1=$?
+          wait $PID1 || STATUS1=$?
           echo "======== Audio Tests ========"
           cat dx12_audio_test_result.log
 
-          wait $PID2; STATUS2=$?
+          wait $PID2 || STATUS2=$?
           echo -e "\n======== GraphicsDevice Tests ========"
           cat dx12_graphics_device_test_result.log
 
-          wait $PID3; STATUS3=$?
+          wait $PID3 || STATUS3=$?
           echo -e "\n======== MemoryLifeCycle Tests ========"
           cat dx12_memory_lifecycle_test_result.log
-
-          wait $PID4; STATUS4=$?
-          echo -e "\n======== Remaining Tests ========"
-          cat dx12_remaining_test_result.log
           
-          # 3. Fail the whole step if ANY of the background tests failed
+          # 4. Fail the whole step if ANY of the background tests failed
           if [ $STATUS1 -ne 0 ] || [ $STATUS2 -ne 0 ] || [ $STATUS3 -ne 0 ] || [ $STATUS4 -ne 0 ]; then
             echo "One or more tests failed!"
             exit 1
@@ -547,27 +547,27 @@ jobs:
           dotnet test --filter Category=MemoryLifeCycle --blame-hang-timeout 5m MonoGame.Tests.dll > vk_memory_lifecycle_test_result.log 2>&1 &
           PID3=$!
           
-          dotnet test --filter "Category!=Audio&Category!=GraphicsDevice&Category!=MemoryLifeCycle" --blame-hang-timeout 5m MonoGame.Tests.dll > vk_remaining_test_result.log 2>&1 &
-          PID4=$!
+          # 2. Run the last test suite in foreground
+          echo "======== Running all tests except Audio, GraphicsDevice, MemoryLifeCycle ========"
+          dotnet test --filter "Category!=Audio&Category!=GraphicsDevice&Category!=MemoryLifeCycle" --blame-hang-timeout 5m MonoGame.Tests.dll
+          STATUS4=$?
           
-          # 2. Wait for ech background processes to finish and print results
-          wait $PID1; STATUS1=$?
+          # 3. Wait for ech background processes to finish and print results
+          STATUS1=0; STATUS2=0; STATUS3=0
+          
+          wait $PID1 || STATUS1=$?
           echo "======== Audio Tests ========"
           cat vk_audio_test_result.log
 
-          wait $PID2; STATUS2=$?
+          wait $PID2 || STATUS2=$?
           echo -e "\n======== GraphicsDevice Tests ========"
           cat vk_graphics_device_test_result.log
 
-          wait $PID3; STATUS3=$?
+          wait $PID3 || STATUS3=$?
           echo -e "\n======== MemoryLifeCycle Tests ========"
           cat vk_memory_lifecycle_test_result.log
-
-          wait $PID4; STATUS4=$?
-          echo -e "\n======== Remaining Tests ========"
-          cat vk_remaining_test_result.log
           
-          # 3. Fail the whole step if ANY of the background tests failed
+          # 4. Fail the whole step if ANY of the background tests failed
           if [ $STATUS1 -ne 0 ] || [ $STATUS2 -ne 0 ] || [ $STATUS3 -ne 0 ] || [ $STATUS4 -ne 0 ]; then
             echo "One or more tests failed!"
             exit 1
